### ISSUE TITLE
Spelling mistake & error in alignment

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#28]
windows version- TEST_V2_3

1. In the data table of All conformation energy, the header is spelt as 'Confirmation'.

![spelling](https://user-images.githubusercontent.com/111036161/187362404-6894c9c2-2c7a-45c5-b773-b020e8f1d0dd.JPG)

2. The alignment of the columns are wrong.

![image (3)](https://user-images.githubusercontent.com/111036161/187401018-79212fa7-233d-4d3b-8992-5f225bdf5467.png)

**Comment by mdaakhan** [comment]
Fixed the spelling

**Comment by SumedhaBhosale** [comment]
Alignment error 

![XESS_AlignmentError](https://user-images.githubusercontent.com/105902516/189325844-d0fa06b8-8a6f-4b3b-bbae-b1af80ee0311.jpg)

**Comment by SumedhaBhosale** [comment]
Hi,

EXE - TEST_V2_7 
Windows machine

Alignment is still wrong
![XESS_AlignmentError_2](https://user-images.githubusercontent.com/105902516/189516146-e106f73b-914f-45e2-b45a-75474fdf8335.jpg)

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1
will be reflected in V_D_2_7
